# イベント用ディレクトリ構造作成の設定ファイル
# このファイルをコピーして directory.config.toml として使用してください
# このコメントは削除しても問題ありません、

[[events]]
date = "20251012"
event_name = "アコスタATC"

[[events.models]]
name = "A"
outreach = true
sns = "https://twitter.com/example_a"

[[events.models]]
name = "B"
outreach = false
sns = "https://twitter.com/example_b"

[[events.models]]
name = "C"
outreach = false

[[events.models]]
name = "D"
outreach = true
