# イベント用ディレクトリ構造作成の設定ファイル
# このファイルをコピーして directory.config.toml として使用してください
# このコメントは削除しても問題ありません、

[[events]]
date = "20251012"
event_name = "アコスタATC"

[[events.models]]
name = "Aさん"
outreach = true
sns = "https://twitter.com/example_a" # sns はオプション

[[events.models]]
name = "Bさん"
outreach = false
sns = "https://twitter.com/example_b" # sns はオプション

[[events.models]]
name = "Cさん"
outreach = false

[[events.models]]
name = "Dさん"
outreach = true
