name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  COVERAGE_THRESHOLD: 50

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create config for type check
        run: cp config.example.ts config.ts

      - name: Type check
        run: deno check tools/**/*.ts tests/**/*.ts

      - name: Lint and Format check
        run: pnpm run lint

      - name: Run tests with coverage
        run: deno task test

      - name: Create coverage summary
        if: always()
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          deno coverage coverage/ --detailed >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
