name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  COVERAGE_THRESHOLD: 50

jobs:
  test:
    name: Test and Coverage (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os != 'ubuntu-latest' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest  # 必須: Linuxでのテスト
          - windows-latest # 参考: Windowsでの互換性確認

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create config for type check and tests
        run: cp config.example.ts config.ts

      - name: Lint and Format check
        run: pnpm run lint

      - name: Run type check, tests, and coverage
        run: deno task test

      - name: Create coverage summary
        if: always()
        env:
          NO_COLOR: 1
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          deno coverage coverage/ >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
